Curso-Python/aula207_ola_django/blog/urls.py
from blog import views
from django.urls import path

app_name = 'blog'

# blog/
urlpatterns = [
    path('', views.blog, name='blog'),
    path('<int:post_id>/', views.post, name='post'),
    path('exemplo/', views.exemplo, name='exemplo'),
]

Curso-Python/aula207_ola_django/home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
]

Curso-Python/aula207_ola_django/project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('home.urls')),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
]

Curso-Python/aula207_ola_django/blog/models.py
from django.db import models

# Create your models here.

Curso-Python/aula207_ola_django/home/models.py
from django.db import models

# Create your models here.

Curso-Python/aula207_ola_django/blog/views.py
from django.shortcuts import render
from blog.data import posts
from typing import Any
from django.http import HttpResponse, Http404

def blog(request):
    
    print('blog')

    context = {
        'text': 'Estamos no Blog',
        'posts': posts
    }
    return render(
        request,
        'blog/index.html',
        context
    )

def post(request: HttpResponse, post_id: int):
    found_post: dict[str, Any] | None = None
    for post in posts:
        if post['id'] == post_id:
            found_post = post
            break

    if found_post is None:
        raise Http404('Post não encontrado')

    context = {
        'post': found_post,
        "title": found_post['title']
    }
    return render(
        request,
        'blog/post.html',
        context
    )

def exemplo(request):
    print('exemplo')

    context = {
        'text': 'Estamos no Exemplo'
    }
    return render(
        request,
        'blog/exemplo.html',
        context
    )

Curso-Python/aula207_ola_django/home/views.py
from django.shortcuts import render


def home(request):
    print('home')

    context = {
            'text': 'Estamos na Home'
    }

    return render(
        request,
        'home/index.html',
        context
    )

Curso-Python/aula207_ola_django/blog/templates/blog/exemplo.html
{% extends 'global/base.html' %}

{% block texto %} {{ text }} {% endblock texto %}

Curso-Python/aula207_ola_django/blog/templates/blog/index.html
{% extends 'global/base.html' %}

{% block texto %} {{ text }} {% endblock texto %}

{% block posts %}
    {% for post in posts %}
        {% include 'global/partials/postblock.html' %}
    {% endfor %}
{% endblock posts %}

Curso-Python/aula207_ola_django/blog/templates/blog/post.html
{% extends 'global/base.html' %}

{% block texto %} {{ text }} {% endblock texto %}

{% block posts %}
<article class="post single-post">
    <h2 class="post__title">
        <a href="{% url "blog:post" post.id %}">
            {{ post.title }}
        </a>
    </h2>
    <div class="post__body">
        {{ post.body }}
    </div>
</article>
{% endblock posts %}

Curso-Python/aula207_ola_django/home/templates/home/index.html
{% extends 'global/base.html' %}

{% block texto %} 
    {{ text }}
{% endblock texto %}

{% block home %}
    <h1>HOME</h1>
{% endblock home %}